### ISSUE TITLE
Coredump write fails with errno 14 (EFAULT) on some systems

### ISSUE THREAD

**Issue by madscientist** [AmadeusITGroup/CoreDumper#1]
I've discovered that on some systems (newer kernels especially), core dump writing is failing with EFAULT while trying to read some of the process memory. Investigation shows that the memory segment in question is the "vvar" segment which contains directly-mapped kernel variables used with VDSO. In older systems that segment either didn't appear in the maps / smaps file at all, or else trying to read it succeeded. But in newer systems I'm seeing the first 4k read (vvar is always 8k AFAICT) succeed, but the second 4k read fails with EFAULT.

Reading various mailing lists etc. it seems like this memory segment isn't needed for a core file anyway, so I just skipped it.

My repository https://github.com/madscientist/google-coredumper cherry-picked the enhancements for RELRO support from here, plus a few fixes from other people and some of my own. My current master HEAD incorporates all the fixes I've found in various GitHub forks (but doesn't pull in support for "corepoint").

The RELRO support changes the coredumper library to parse the proc smaps file instead of proc maps, so my fix involves reading the VmFlags value from smaps and omitting any memory segment which has the "dd" (VM_DONTDUMP) flag set.

FYI...

**Comment by Romain-Geissler-1A** [comment]
Hi,

Replying many years after you initially opened this issue, sorry for that...

Indeed you did a good work at cherry-picking fixes from multiple places. Two years ago I have actually rebased/cherry-pick most (all ?) your commits inside this fork (for us corepoint is still in use now, eventually I think even we on our side we will drop it). I have just pushed a fix here for relro binary with a "big" first page fully read-only: https://github.com/AmadeusITGroup/CoreDumper/commit/c146060e80fcd90c3b5dab0217986dab13732fcb

I intend to keep our "amadeus" branches clearly separated from the "upstream" things like the historical repo and the multiple github forks. Note the "amadeus/master" branch uses rebase strategy for each of our Amadeus only patches, so it's not reliable to fork from it, the other amadeus branches have an immutable history.

Note: since we are migrating to openshift workloads eventually, and since openshift will for security reason not enable the ptrace capability, eventually we will stop using this library, and instead favor code dump generation via CRIU and the builtin CRIU tool to convert a process CRIU "snapshot" into a core dump. However we are still some years away from this, and in the meantime we have to keep this lib working for investigation purposes.

I will close this issue since in this repo I have cherry-picked your work. Thanks for reporting it (and thanks for maintaining GNU make that we use a lot in my organization !)

Cheers,
Romain
